"use strict";
const express=require("express");
const path=require("path");
const fs=require("fs");
const multer=require("multer");
const router=express.Router();
const controller=require("../controllers/productMediaController");
const adminAuth=require("../middleware/adminAuth");
const uploadDir=path.join(process.cwd(),"public/uploads/products/gallery");
fs.mkdirSync(uploadDir,{recursive:true});
const storage=multer.diskStorage({destination:(req,file,cb)=>cb(null,uploadDir),filename:(req,file,cb)=>{const ext=path.extname(file.originalname).toLowerCase();cb(null,`${Date.now()}-${Math.round(Math.random()*1e9)}${ext}`);}});
const upload=multer({storage,limits:{fileSize:8*1024*1024,files:10},fileFilter:(req,file,cb)=>{const ok=["image/jpeg","image/png","image/webp"].includes(file.mimetype);cb(ok?null:new Error("Only JPG, PNG and WEBP images are allowed."),ok);}});
router.get("/public/:productId",controller.getPublicGallery);
router.use(adminAuth);
router.get("/:productId",controller.getAdminGallery);
router.post("/:productId",upload.array("images",10),controller.uploadImages);
router.patch("/image/:imageId",controller.updateImage);
router.patch("/image/:imageId/primary",controller.setPrimary);
router.delete("/image/:imageId",controller.deleteImage);
module.exports=router;
